// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: register.proto

package com.dyw.jwt.proto.register;

public interface RegisterResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:register.RegisterResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool succeed = 1;</code>
   */
  boolean getSucceed();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
