// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: register.proto

package com.dyw.jwt.proto.register;

public final class Register {
  private Register() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_register_RegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_register_RegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_register_RegisterResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_register_RegisterResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016register.proto\022\010register\"R\n\017RegisterRe" +
      "quest\022\020\n\010username\030\001 \001(\t\022\020\n\010password\030\002 \001(" +
      "\t\022\r\n\005email\030\003 \001(\t\022\014\n\004code\030\004 \001(\t\"4\n\020Regist" +
      "erResponse\022\017\n\007succeed\030\001 \001(\010\022\017\n\007message\030\002" +
      " \001(\t2O\n\010register\022C\n\010Register\022\031.register." +
      "RegisterRequest\032\032.register.RegisterRespo" +
      "nse\"\000B\036\n\032com.dyw.jwt.proto.registerP\001b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_register_RegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_register_RegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_register_RegisterRequest_descriptor,
        new java.lang.String[] { "Username", "Password", "Email", "Code", });
    internal_static_register_RegisterResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_register_RegisterResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_register_RegisterResponse_descriptor,
        new java.lang.String[] { "Succeed", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
