// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: register.proto

package com.dyw.jwt.proto.register;

public interface RegisterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:register.RegisterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 2;</code>
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string email = 3;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 3;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string code = 4;</code>
   */
  java.lang.String getCode();
  /**
   * <code>string code = 4;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();
}
