// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: code.proto

package com.dyw.jwt.proto.code;

public final class Code {
  private Code() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getcode_CodeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getcode_CodeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getcode_CodeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getcode_CodeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ncode.proto\022\007getcode\"\034\n\013CodeRequest\022\r\n\005" +
      "email\030\001 \001(\t\"0\n\014CodeResponse\022\017\n\007succeed\030\001" +
      " \001(\010\022\017\n\007message\030\002 \001(\t2A\n\007getCode\0226\n\007getC" +
      "ode\022\024.getcode.CodeRequest\032\025.getcode.Code" +
      "ResponseB\032\n\026com.dyw.jwt.proto.codeP\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_getcode_CodeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_getcode_CodeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getcode_CodeRequest_descriptor,
        new java.lang.String[] { "Email", });
    internal_static_getcode_CodeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_getcode_CodeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getcode_CodeResponse_descriptor,
        new java.lang.String[] { "Succeed", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
