// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: code.proto

package com.dyw.jwt.proto.code;

public interface CodeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:getcode.CodeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 1;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
