server:
  port: 9091

spring:
  application:
    name: service-consumer
  cloud:
    consul:
      host: 124.222.35.20
      port: 8500
      discovery:
        register: false
        instance-id: ${spring.application.name}-01
        service-name: ${spring.application.name}
        port: ${server.port}
        prefer-ip-address: true
        ip-address: ${spring.cloud.client.ip-address}


grpc:
  client:
    cloud-grpc-server:
      address: 'discovery:///cloud-grpc-server'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: PLAINTEXT
